"""
Twitter API-related configuration.
"""

ACCOUNTS = [
	{
		'ACCESS_TOKEN': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
		'ACCESS_TOKEN_SECRET': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
		'CONSUMER_KEY': 'XXXXXXXXXXXXXXXXXXXXXXXXX',
		'CONSUMER_SECRET': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
	}
]
