#!/usr/bin/env python3

"""
The meta tool extracts and pretty-prints metadata from files generated by EvenTDT's tools.
To run the tool, use:

.. code-block:: bash

    ./tools/meta.py \\
    --file idf.json

The tool automatically highlights the parameters that were provided in the command.
This does not work, however, with single-character parameters since the meta tool is unaware of their mappings.

The full list of accepted arguments:

    - ``-f --file``     *<Required>* The file from where to print the metadata, which must have been generated by an EvenTDT tool.
"""

import argparse
import json
import re

def setup_args():
    """
    Set up and get the list of command-line arguments.

    Accepted arguments:

        - ``-f --file``     *<Required>* The file from where to print the metadata, which must have been generated by an EvenTDT tool.

    :return: The command-line arguments.
    :rtype: :class:`argparse.Namespace`
    """

    parser = argparse.ArgumentParser(description="Extract the metadata from files generated by EvenTDT's tools.")

    parser.add_argument('-f', '--file', type=str, required=True,
                        help='<Required> The file from where to print the metadata, which must have been generated by an EvenTDT tool.')

    args = parser.parse_args()
    return args

def main():
    """
    Main program loop.
    """

    args = setup_args()
    pprint(args.file)

def pprint(file):
    """
    Pretty-print the metadata from the given file.

    :param file: The path to the file from where to print the metadata.
    :type file: str
    """

    with open(file) as f:
        data = json.loads(''.join(f.readlines()))
        cmd, pcmd = data['cmd'], data['pcmd']
        del data

        """
        Print the general metadata first.
        """
        print(f"Generated on { cmd['_date'] }")
        print("=======================================")
        print(f"{ cmd['_cmd'] }")
        print()

        """
        Extract the parameters that were actually provided.
        """
        param_pattern = re.compile("--(.+?)(\s|$)")
        params = [ param[0] for param in param_pattern.findall(cmd['_cmd']) ]

        """
        Go through the rest of the metadata and print it.
        Skip the general metadata generated by the tool, which starts with an underscore.
        """
        for key, value in cmd.items():
            if key.startswith('_'):
                continue

            """
            If the parameter was given as a command-line parameter, highlight it.
            """
            key = key.replace('_', '-')
            if key in params:
                print(f"\033[0;36m{ key }: { value }\033[0;39m")
            else:
                print(f"{ key }: { value }")

if __name__ == "__main__":
    main()
